# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Country')),
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Country Code')),
                ('website', models.URLField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='State')),
                ('website', models.URLField(blank=True, max_length=60)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographyapp.country', verbose_name='Country')),
            ],
        ),
    ]
