# Generated by Django 4.1.10 on 2025-09-18 18:35

import businessapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('reg_no', models.CharField(max_length=30, unique=True, verbose_name='Registration Number')),
                ('doc', models.FileField(upload_to=businessapp.models.upload_to_organization, verbose_name='Document')),
                ('is_active', models.BooleanField(default=False, verbose_name='Verified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=30, verbose_name='Entity')),
                ('doc', models.CharField(max_length=30, verbose_name='Document')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='OrgStateGstOps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='GSTIN')),
                ('doc', models.FileField(blank=True, null=True, upload_to=businessapp.models.upload_to_org_gst, verbose_name='Document')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.org', verbose_name='Organization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographyapp.state', verbose_name='State')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.org', verbose_name='Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
