# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApp',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('apk', models.CharField(blank=True, max_length=30, null=True, verbose_name='Android')),
                ('ios', models.CharField(blank=True, max_length=30, null=True, verbose_name='iOS')),
            ],
        ),
        migrations.CreateModel(
            name='MobileAppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=90, null=True, verbose_name='Subject')),
                ('comment', models.TextField(blank=True, verbose_name='Description')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapp.mobileapp', verbose_name='App')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
