# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Username')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('pan', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN')),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhar')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP')),
                ('is_active', models.BooleanField(default=False, verbose_name='User Status')),
                ('msg', models.CharField(blank=True, max_length=90, null=True, verbose_name='Account Blocked (Reason)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='User Verified')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Palanhaar Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Palanhaar Admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
