# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.db import migrations, models
import django.db.models.deletion
import productapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Brand')),
                ('image', models.ImageField(upload_to=productapp.models.upload_to_brand_image, verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_show', models.BooleanField(default=True, verbose_name='Show Brand in Product Catalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='Organization')),
                ('address', models.TextField(verbose_name='Address')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('desc', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=productapp.models.upload_to_product_image_primary, verbose_name='Image')),
                ('weight', models.CharField(blank=True, max_length=15, null=True, verbose_name='Weight')),
                ('net_weight', models.CharField(blank=True, max_length=15, null=True, verbose_name='Net Weight')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_available', models.BooleanField(default=True, verbose_name='Availability')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_brand', to='productapp.brand', verbose_name='Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProdSubCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Subcategory')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodsubcat_prodcat', to='productapp.prodcat', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProdMacroCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Macrocategory')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodmacrocat_prodcat', to='productapp.prodcat', verbose_name='Category')),
                ('sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodmacrocat_prodsubcat', to='productapp.prodsubcat', verbose_name='Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProdImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=productapp.models.upload_to_product_image, verbose_name='Image')),
                ('prod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='productimages', to='productapp.prod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='prod',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_prodcat', to='productapp.prodcat', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='prod',
            name='macro_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_prodmacrocat', to='productapp.prodmacrocat', verbose_name='Macrocategory'),
        ),
        migrations.AddField(
            model_name='prod',
            name='sub_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_prodsubcat', to='productapp.prodsubcat', verbose_name='Subcategory'),
        ),
        migrations.CreateModel(
            name='OrgBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgbrand_brand', to='productapp.brand', verbose_name='Brand')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgbrand_org', to='productapp.org', verbose_name='Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
