# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.db import migrations, models
import django.db.models.deletion
import indianrailwaysapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessapp', '0001_initial'),
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrHelplineNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Helpline Number')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='OrgShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RailDivision',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Division Code')),
                ('name', models.CharField(max_length=30, verbose_name='Division')),
            ],
        ),
        migrations.CreateModel(
            name='RailStation',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Station Code')),
                ('name', models.CharField(max_length=60, verbose_name='Railway Station')),
                ('platforms', models.CharField(blank=True, max_length=15, null=True, verbose_name='Platform')),
            ],
        ),
        migrations.CreateModel(
            name='RailStationCategoy',
            fields=[
                ('category', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Station Category')),
            ],
        ),
        migrations.CreateModel(
            name='RailZone',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Zone Code')),
                ('name', models.CharField(max_length=60, verbose_name='Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='Shop Name')),
                ('image', models.ImageField(upload_to=indianrailwaysapp.models.upload_to_shop_image_primary, verbose_name='Image')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number')),
                ('lat', models.CharField(max_length=15, verbose_name='Latitdue')),
                ('lon', models.CharField(max_length=15, verbose_name='Longitude')),
                ('platform_a', models.CharField(blank=True, max_length=6, null=True, verbose_name='Primary Platform')),
                ('platform_b', models.CharField(blank=True, max_length=6, null=True, verbose_name='Secondary Platform')),
                ('is_open', models.BooleanField(default=False, verbose_name='Open')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_cash', models.BooleanField(default=False, verbose_name='Cash')),
                ('is_card', models.BooleanField(default=False, verbose_name='Card')),
                ('is_upi', models.BooleanField(default=False, verbose_name='UPI')),
                ('is_osop', models.BooleanField(default=False, verbose_name='OSOP Stall')),
                ('is_baby', models.BooleanField(default=False, verbose_name='Baby Food')),
                ('is_medical', models.BooleanField(default=False, verbose_name='OTC Medicine')),
                ('message', models.TextField(blank=True, max_length=150, null=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Train No')),
                ('train_name', models.CharField(max_length=60, verbose_name='Train Name')),
                ('run_sun', models.BooleanField(default=False, verbose_name='Train runs on Sunday')),
                ('run_mon', models.BooleanField(default=False, verbose_name='Train runs on Monday')),
                ('run_tue', models.BooleanField(default=False, verbose_name='Train runs on Tuesday')),
                ('run_wed', models.BooleanField(default=False, verbose_name='Train runs on Wednesday')),
                ('run_thu', models.BooleanField(default=False, verbose_name='Train runs on Thursday')),
                ('run_fri', models.BooleanField(default=False, verbose_name='Train runs on Friday')),
                ('run_sat', models.BooleanField(default=False, verbose_name='Train runs on Saturday')),
                ('run_daily', models.BooleanField(default=False, verbose_name='Train runs Daily')),
                ('duration', models.CharField(blank=True, max_length=15, null=True, verbose_name='Duration')),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_station_from', to='indianrailwaysapp.railstation', verbose_name='Station From')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_station_to', to='indianrailwaysapp.railstation', verbose_name='Station To')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='Station No')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('distance', models.IntegerField(verbose_name='Distance (in KM)')),
                ('platform', models.CharField(blank=True, max_length=6, null=True, verbose_name='Platform')),
                ('dep_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('arv_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('halt_time', models.TimeField(blank=True, null=True, verbose_name='Halt Time')),
                ('rev_dir', models.BooleanField(default=False, verbose_name='Reverse Direction')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.railstation', verbose_name='Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.train', verbose_name='Train')),
            ],
        ),
        migrations.CreateModel(
            name='ShopLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=30, unique=True, verbose_name='License Number')),
                ('doc', models.FileField(upload_to=indianrailwaysapp.models.upload_to_shop_license, verbose_name='Document')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_stock', models.BooleanField(default=True, verbose_name='Stock')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Selling Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.prod', verbose_name='Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopGst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.orgstategstops', verbose_name='Organizaton-State')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.org', verbose_name='Organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopFssaiLic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=30, unique=True, verbose_name='FSSAI License Number')),
                ('doc', models.FileField(upload_to=indianrailwaysapp.models.upload_to_shop_fssai, verbose_name='Document')),
                ('start_date', models.DateField(blank=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=True, verbose_name='Current')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Valid')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopBusinessType',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('shop_type', models.ManyToManyField(related_name='shoptypelist', to='indianrailwaysapp.shoptype')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shopbusinesstype', verbose_name='Shop Business Type'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shoptype', verbose_name='Shop Type'),
        ),
        migrations.AddField(
            model_name='shop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.railstation', verbose_name='Railway Station'),
        ),
        migrations.AddField(
            model_name='railstation',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.railstationcategoy', verbose_name='Railway Station Category'),
        ),
        migrations.AddField(
            model_name='railstation',
            name='div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.raildivision', verbose_name='Railway Division'),
        ),
        migrations.AddField(
            model_name='railstation',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.railzone', verbose_name='Railway Zone'),
        ),
        migrations.AddField(
            model_name='raildivision',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.railzone', verbose_name='Railway Zone'),
        ),
        migrations.CreateModel(
            name='OrgShopEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='Manager')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.org', verbose_name='Organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
