# Generated by Django 4.1.10 on 2025-09-18 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographyapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessapp', '0002_initial'),
        ('indianrailwaysapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgshopemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='orgshop',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessapp.org', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='orgshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indianrailwaysapp.shop', verbose_name='Shop'),
        ),
        migrations.AddField(
            model_name='irhelplinenumber',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographyapp.state', verbose_name='State'),
        ),
    ]
